### ISSUE TITLE
is this an error?

### ISSUE THREAD

**Issue by mengod-gh** [nicks96432/mltd-asset-downloader#34]
I solved

**Comment by nicks96432** [comment]
Sorry for the late reply! I'm quite busy after the summer vacation.  
The javascript version of this program (v1) will not receive feature update anymore basically, and v2 is currently devaloping in my little free time. 🥲  
By the way, can you share your solution? I'm curious about what happened.

**Comment by nicks96432** [comment]
I'm closing issue now. Feel free to reopen it again. Any feedback is appreciated!
